filebeat.inputs:

- type: log

  enabled: true

  paths:
    - /var/log/messages

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false


setup.template.settings:
  index.number_of_shards: 3


setup.kibana:

 host: "10.217.129.253:5601"


output.logstash:
  hosts: ["10.217.129.253:5044"]


processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

