---
- hosts: all
  become: true

  tasks:

  - name: download filebeat rpm package
    get_url: 
      url: https://github.com/alagesh146/beats/raw/master/filebeat-6.6.2-x86_64.rpm
      dest: /tmp
      mode: 0755
    
  - name: install the rpm
    yum:
     name: /tmp/filebeat-6.6.2-x86_64.rpm
     state: present
     
  - name: download config file
    get_url: 
      url: https://raw.githubusercontent.com/alagesh146/beats/master/filebeat.yml
      dest: /etc/filebeat/
      backup: yes
      force: yes
      
  
  - name: systemctl reload 
    shell: systemctl daemon-reload

    
  - name: enable filebeat service and ensure it is not masked
    systemd:
     name: filebeat
     enabled: yes
     masked: no
  - name: Make sure a service is running
    systemd:
     state: started
     name: filebeat
 
